name: Build Android AAR

on:
  workflow_dispatch:

jobs:
  tag-version:
    name: 📌 Tag Version
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.increment_tag.outputs.TAG }}

    steps:
      - uses: actions/checkout@v4

      - name: Increment Version Tag
        id: increment_tag
        run: |
          git fetch --tags
          current_tag=$(git tag --list "v*" | sort -V | tail -n 1)

          if [ -z "$current_tag" ]; then
            new_tag="v1.0.0"
          else
            version=${current_tag#v}
            IFS='.' read -r -a version_parts <<< "$version"
            patch=$((version_parts[2] + 1))
            new_tag="v${version_parts[0]}.${version_parts[1]}.$patch"
          fi

          echo "New tag: $new_tag"
          echo "::set-output name=TAG::$new_tag"

      - name: Create Git Tag
        run: |
          git tag ${{ steps.increment_tag.outputs.TAG }}
          git push origin ${{ steps.increment_tag.outputs.TAG }}

  build-aar:
    name: 🛠 Build AAR
    runs-on: ubuntu-latest
    needs: tag-version

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build AAR
        run: ./gradlew clean assembleRelease

      - name: Upload AAR to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aar
          path: app/build/outputs/aar/*.aar

      - name: Upload AAR to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: app/build/outputs/aar/*.aar
          tag: ${{ needs.tag-version.outputs.tag }}
          overwrite: true
          body: "Release ${{ needs.tag-version.outputs.tag }}"
